version: '3.8'

services:
  postgres-db:
    image: postgres
    restart: no
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - 5432:5432

volumes:
  redis-db:
    driver: local