version: '3.8'

services:
  redis-db:
    image: redis:7.0.5-alpine
    restart: unless-stopped
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    command: "redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}"
    volumes:
      - redis-db:/data

volumes:
  redis-db:
    driver: local